INSERT INTO table1 (id, name, age, city) VALUES
(1, 'John Doe', 28, 'New York'),
(2, 'Jane Smith', 34, 'Los Angeles'),
(3, 'Robert Brown', 45, 'Chicago'),
(4, 'Emily Davis', 23, 'Miami'),
(5, 'Michael Wilson', 32, 'Dallas'),
(6, 'Sarah Moore', 41, 'Houston'),
(7, 'David Taylor', 29, 'Phoenix'),
(8, 'Laura Anderson', 36, 'San Diego'),
(9, 'James Thomas', 27, 'Seattle'),
(10, 'Linda Jackson', 40, 'San Francisco'),
(11, 'Charles White', 55, 'Austin'),
(12, 'Anna Harris', 33, 'Las Vegas'),
(13, 'Thomas Clark', 38, 'Orlando'),
(14, 'Nancy Lewis', 24, 'Boston'),
(15, 'Gary Walker', 50, 'Denver'),
(16, 'Jessica Allen', 31, 'Portland'),
(17, 'Brian Young', 44, 'Washington'),
(18, 'Karen King', 25, 'Minneapolis'),
(19, 'Steven Scott', 39, 'Atlanta'),
(20, 'Patricia Adams', 47, 'Salt Lake City');